name: Build&Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set Default Scheme
        run: |
          scheme_list=$(xcodebuild -list -json | tr -d "\n")
          default=$(echo $scheme_list | ruby -e "require 'json'; puts JSON.parse(STDIN.gets)['project']['targets'][0]")
          echo $default | cat >default
          echo Using default scheme: $default
      - name: Build and test macOS
        env:
          scheme: ${{ 'default' }}
          platform: ${{ 'macOS' }}
        run: |
          xcodebuild clean build test -project EssentialFeed.xcodeproj -scheme "CI_macOS" CODE_SIGNING_IDENTITY="" CODE_SIGNING_REQUIERED=NO -sdk macosx -destination "platform=macOS" ONLY_ACTIVE_ARCH=YES
      - name: Build and test iOS
        env:
          scheme: ${{ 'default' }}
          platform: ${{ 'iOS' }}
        run: |
          xcodebuild clean build test -project EssentialFeed.xcodeproj -scheme "CI_iOS" CODE_SIGNING_IDENTITY="" CODE_SIGNING_REQUIERED=NO -sdk iphonesimulator -destination "platform=iOS Simulator,OS=15.2,name=iPhone 13" ONLY_ACTIVE_ARCH=YES